%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-mapviz
Version:        2.4.8
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mapviz package

License:        BSD
URL:            https://github.com/swri-robotics/mapviz
Source0:        %{name}-%{version}.tar.gz

Requires:       freeglut-devel
Requires:       glew-devel
Requires:       libXi-devel
Requires:       libXmu-devel
Requires:       qt5-qtbase
Requires:       ros-jazzy-cv-bridge
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-image-transport
Requires:       ros-jazzy-mapviz-interfaces
Requires:       ros-jazzy-marti-common-msgs
Requires:       ros-jazzy-pluginlib
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-rqt-gui
Requires:       ros-jazzy-rqt-gui-cpp
Requires:       ros-jazzy-std-srvs
Requires:       ros-jazzy-swri-math-util
Requires:       ros-jazzy-swri-transform-util
Requires:       ros-jazzy-tf2
Requires:       ros-jazzy-tf2-geometry-msgs
Requires:       ros-jazzy-tf2-ros
Requires:       yaml-cpp-devel
Requires:       ros-jazzy-ros-workspace
BuildRequires:  freeglut-devel
BuildRequires:  glew-devel
BuildRequires:  libXi-devel
BuildRequires:  libXmu-devel
BuildRequires:  pkgconfig
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-cv-bridge
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-image-transport
BuildRequires:  ros-jazzy-mapviz-interfaces
BuildRequires:  ros-jazzy-marti-common-msgs
BuildRequires:  ros-jazzy-pluginlib
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-ros-environment
BuildRequires:  ros-jazzy-rqt-gui
BuildRequires:  ros-jazzy-rqt-gui-cpp
BuildRequires:  ros-jazzy-std-srvs
BuildRequires:  ros-jazzy-swri-math-util
BuildRequires:  ros-jazzy-swri-transform-util
BuildRequires:  ros-jazzy-tf2
BuildRequires:  ros-jazzy-tf2-geometry-msgs
BuildRequires:  ros-jazzy-tf2-ros
BuildRequires:  yaml-cpp-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
mapviz

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 2.4.8-1
- Autogenerated by Bloom

* Tue May 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 2.4.7-1
- Autogenerated by Bloom

* Wed Apr 02 2025 Southwest Research Institute <swri-robotics@swri.org> - 2.4.6-1
- Autogenerated by Bloom

* Mon Jan 20 2025 Southwest Research Institute <swri-robotics@swri.org> - 2.4.5-1
- Autogenerated by Bloom

* Mon Dec 09 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.4.4-1
- Autogenerated by Bloom

* Wed Sep 18 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.4.3-1
- Autogenerated by Bloom

* Fri Aug 09 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.4.1-1
- Autogenerated by Bloom

* Fri Aug 09 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.4.0-1
- Autogenerated by Bloom

* Thu Apr 18 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.3.0-3
- Autogenerated by Bloom

* Wed Mar 06 2024 Southwest Research Institute <swri-robotics@swri.org> - 2.3.0-2
- Autogenerated by Bloom

